name: CI

on:
  push:
    branches: [ "deploy/**" ]

jobs:
  build:
    run-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: |
          echo "Hello Flows"